from ex0 import FlameFactory, AquaFactory

print('Testing factory')
flame_factory = FlameFactory()
flame = flame_factory.create_base()
print(flame.describe())
print(flame.attack())
pyro = flame_factory.create_evolved()
print(pyro.describe())
print(pyro.attack())
print('')

print('Testing factory')
aqua_factory = AquaFactory()
aqua = aqua_factory.create_base()
print(aqua.describe())
print(aqua.attack())
torra = aqua_factory.create_evolved()
print(torra.describe())
print(torra.attack())
print('')

print('Testing battle')
print(flame.describe())
print(' vs.')
print(aqua.describe())
print(' fight!')
print(flame.attack())
print(aqua.attack())
